### ISSUE TITLE
HTML Sample not works with Chrome on some computers

### ISSUE THREAD

**Issue by YZahringer** [polyright/PaymentTerminal-URI-Scheme#4]
In some computers Chrome runs a Google Search instead of launching Payment Terminal application.

**Comment by sverleye** [comment]
Et tu résous comment cela ?

Sébastien Verleye
CTO

Mobile : +4179 793 89 72
Phone  : +4127 303 50 34
[cid:image008.png@01D20AA2.D2E7C4F0]<https://www.polyright.com/>
Sion, Lausanne, Zürich
Follow us !
[cid:image001.png@01D0EA13.EE4DF8F0]<https://www.linkedin.com/company/polyright-sa>

NEW : Application polyright cashless disponible !

[cid:image001.png@01D20AAB.AEDCD880]<http://onelink.to/cashless>  [cid:image002.png@01D20AAB.AEDCD880] <http://onelink.to/cashless>

ou utilisez la version web cashless.polyright.com<https://cashless.polyright.com/>

De : Yann Zahringer Ferrando [mailto:notifications@github.com]
Envoyé : jeudi, 28 septembre 2017 13:46
À : polyright/PaymentTerminal-URI-Scheme <PaymentTerminal-URI-Scheme@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [polyright/PaymentTerminal-URI-Scheme] HTML Sample not works with Chrome on some computers (#4)


In some computers Chrome runs a Google Search instead of launching Payment Terminal application.
